In [ ]:
import numpy as np
from astropy.io import fits
from astroscrappy import detect_cosmics
from astropy.stats import sigma_clipped_stats, SigmaClip
import photutils
# from photutils import detect_threshold, detect_sources
# from photutils.utils import circular_footprint
import matplotlib.pyplot as plt

mydpi = 150
plt.rcParams.update({'font.size': 12})

In [ ]:
datapath = r"/"

In [ ]:
# raw science frame

raws = []
for i in range(6,10):
    data = fits.getdata(datapath + '/M31-00'+ str(i) + 'G.fit', ext=0)
    raws.append(data)
for i in range(10,26):
    data = fits.getdata(datapath + '/M31-0'+ str(i) + 'G.fit', ext=0)
    raws.append(data)
    

In [ ]:
# # Master bias

# bias = []
# for i in range(1,10):
#     data = fits.getdata(datapath + '/Bias-00'+ str(i) + '.fit', ext=0)
#     bias.append(data)

# data = fits.getdata(datapath + '/Bias-010'+ '.fit', ext=0)
# bias.append(data)

# master_bias = np.median(bias, axis=0)

In [ ]:
# Master dark

dark_for_science = []
for i in range(1,10):
    data = fits.getdata(datapath + '/Dark60-00'+ str(i) + '.fit', ext=0)
    dark_for_science.append(data)
for i in range(10,20):
    data = fits.getdata(datapath + '/Dark60-0'+ str(i) + '.fit', ext=0)
    dark_for_science.append(data)

master_dark_for_science = np.median(dark_for_science, axis=0)

In [ ]:
# Master flat

flats = []
for i in range(1,10):
    data = fits.getdata(datapath + '/Flats-00'+ str(i) + 'G.fit', ext=0)
    head = fits.getheader(datapath + '/Flats-00'+ str(i) + 'G.fit', ext=0)
    flats.append(data)

data = fits.getdata(datapath + '/Flats-010G.fit', ext=0)
flats.append(data)


dark_for_flats = []
for i in range(1,10):
    data = fits.getdata(datapath + '/Dark0_2-00'+ str(i) + '.fit', ext=0)
    head = fits.getheader(datapath + '/Dark0_2-00'+ str(i) + '.fit', ext=0)
    dark_for_flats.append(data)

data = fits.getdata(datapath + '/Dark0_2-010.fit', ext=0)
dark_for_flats.append(data)


flats_ = np.zeros_like(flats) * 1.0
for i in range(len(flats)):
    flats_[i] = flats[i] - dark_for_flats[i]
    
master_flat = np.median(flats_, axis=0)
print(master_flat)
master_flat_mean = np.mean(master_flat)

[[ 666.5  701.   711.5 ...  547.   581.   537. ]
 [1014.   943.   992.5 ...  797.5  826.5  807.5]
 [ 988.   995.  1031.5 ...  826.   825.   840. ]
 ...
 [1005.5  980.   992.  ...  953.   927.5  952.5]
 [ 993.5  963.5  984.5 ...  980.5  955.5  925. ]
 [ 129.5  134.   134.5 ...  132.   136.   133.5]]


In [103]:
science_frames = np.zeros_like(raws) * 1.0
for i in range(len(raws)): 
    science_frames[i] = (raws[i] - master_dark_for_science)/(master_flat / master_flat_mean)

In [104]:
# for i in range(len(science_frames)):
#     plt.figure(figsize=(12,12), dpi = mydpi)
#     plt.imshow(science_frames[i])
#     plt.show()

In [ ]:
datapath = r"/Whirlpool Galaxy\LIGHT\R"

In [ ]:
# raw science frame

raws = []
for i in range(0,10):
    data = fits.getdata(datapath + '/60.00s-000'+ str(i) + '.fits', ext=0)
    head = fits.getheader(datapath + '/60.00s-000'+ str(i) + '.fits', ext=0)
    print(head)
    raws.append(data)
head

SIMPLE  =                    T / C# FITS                                        BITPIX  =                   16 /                                                NAXIS   =                    2 / Dimensionality                                 NAXIS1  =                 4096 /                                                NAXIS2  =                 4096 /                                                BZERO   =                32768 /                                                EXTEND  =                    T / Extensions are permitted                       IMAGETYP= 'LIGHT'              / Type of exposure                               EXPOSURE=                 60.0 / [s] Exposure duration                          EXPTIME =                 60.0 / [s] Exposure duration                          DATE-LOC= '2023-04-20T22:44:11.869' / Time of observation (local)               DATE-OBS= '2023-04-20T20:44:11.869' / Time of observation (UTC)                 XBINNING=                    1 / X axis 

SIMPLE  =                    T / C# FITS                                        BITPIX  =                   16 /                                                NAXIS   =                    2 / Dimensionality                                 NAXIS1  =                 4096 /                                                NAXIS2  =                 4096 /                                                BZERO   =                32768 /                                                EXTEND  =                    T / Extensions are permitted                       IMAGETYP= 'LIGHT'              / Type of exposure                               EXPOSURE=                 60.0 / [s] Exposure duration                          EXPTIME =                 60.0 / [s] Exposure duration                          DATE-LOC= '2023-04-20T22:46:35.257' / Time of observation (local)               DATE-OBS= '2023-04-20T20:46:35.257' / Time of observation (UTC)                 XBINNING=                    1 / X axis 

SIMPLE  =                    T / C# FITS                                        BITPIX  =                   16 /                                                NAXIS   =                    2 / Dimensionality                                 NAXIS1  =                 4096 /                                                NAXIS2  =                 4096 /                                                BZERO   =                32768 /                                                EXTEND  =                    T / Extensions are permitted                       IMAGETYP= 'LIGHT'              / Type of exposure                               EXPOSURE=                 60.0 / [s] Exposure duration                          EXPTIME =                 60.0 / [s] Exposure duration                          DATE-LOC= '2023-04-20T22:48:58.667' / Time of observation (local)               DATE-OBS= '2023-04-20T20:48:58.667' / Time of observation (UTC)                 XBINNING=                    1 / X axis 

SIMPLE  =                    T / C# FITS                                        BITPIX  =                   16 /                                                NAXIS   =                    2 / Dimensionality                                 NAXIS1  =                 4096 /                                                NAXIS2  =                 4096 /                                                BZERO   =                32768 /                                                EXTEND  =                    T / Extensions are permitted                       IMAGETYP= 'LIGHT'              / Type of exposure                               EXPOSURE=                 60.0 / [s] Exposure duration                          EXPTIME =                 60.0 / [s] Exposure duration                          DATE-LOC= '2023-04-20T22:51:22.123' / Time of observation (local)               DATE-OBS= '2023-04-20T20:51:22.123' / Time of observation (UTC)                 XBINNING=                    1 / X axis 

SIMPLE  =                    T / C# FITS                                        BITPIX  =                   16 /                                                NAXIS   =                    2 / Dimensionality                                 NAXIS1  =                 4096 /                                                NAXIS2  =                 4096 /                                                BZERO   =                32768 /                                                EXTEND  =                    T / Extensions are permitted                       IMAGETYP= 'LIGHT'              / Type of exposure                               EXPOSURE=                 60.0 / [s] Exposure duration                          EXPTIME =                 60.0 / [s] Exposure duration                          DATE-LOC= '2023-04-20T22:53:45.514' / Time of observation (local)               DATE-OBS= '2023-04-20T20:53:45.514' / Time of observation (UTC)                 XBINNING=                    1 / X axis 

SIMPLE  =                    T / C# FITS                                        
BITPIX  =                   16 /                                                
NAXIS   =                    2 / Dimensionality                                 
NAXIS1  =                 4096 /                                                
NAXIS2  =                 4096 /                                                
BZERO   =                32768 /                                                
EXTEND  =                    T / Extensions are permitted                       
IMAGETYP= 'LIGHT'              / Type of exposure                               
EXPOSURE=                 60.0 / [s] Exposure duration                          
EXPTIME =                 60.0 / [s] Exposure duration                          
DATE-LOC= '2023-04-20T22:54:57.141' / Time of observation (local)               
DATE-OBS= '2023-04-20T20:54:57.141' / Time of observation (UTC)                 
XBINNING=                   

In [108]:
science_frames = np.zeros_like(raws) * 1.0
for i in range(len(raws)): 
    science_frames[i] = (raws[i] - master_dark_for_science)/(master_flat / master_flat_mean)

In [ ]:
science_frames_clean = np.zeros_like(raws) * 1.0
for i in range(0,10):
    mask, science_frames_clean[i] = detect_cosmics(science_frames[i], inmask=None, sigclip=4.0, sigfrac=0.3,
        objlim=5.0, gain=1.15, readnoise=9, satlevel=65536, niter=4,
        sepmed=True, cleantype='meanmask', fsmode='median', psfmodel='gauss',
        psffwhm=2.5, psfsize=7, psfk=None, psfbeta=4.765, verbose=False)

#     plt.figure(figsize=(12,12), dpi = mydpi)
#     plt.imshow(science_frames_clean[i])
#     plt.show()

# fits.writeto(r'/science_whirpool_cosmic.fits', _clean, head, overwrite=True)

In [ ]:
# data = fits.getdata(datapath + '/60.00s-0000.fits', ext=0)
# head = fits.getheader(datapath + '/60.00s-0000.fits', ext=0)

# mask, _clean = detect_cosmics(data, inmask=None, sigclip=4.0, sigfrac=0.3,
#     objlim=5.0, gain=0, readnoise=9, satlevel=65536, niter=4,
#     sepmed=True, cleantype='meanmask', fsmode='median', psfmodel='gauss',
#     psffwhm=2.5, psfsize=7, psfk=None, psfbeta=4.765, verbose=False)

# plt.figure(figsize=(12,12), dpi = mydpi)
# plt.imshow(_clean)
# plt.show()
# print(_clean)

# fits.writeto(r'/science_whirpool_cosmic_9.fits', _clean, head, overwrite=True)

In [ ]:
data = fits.getdata(datapath + '/60.00s-0000.fits', ext=0)
head = fits.getheader(datapath + '/60.00s-0000.fits', ext=0)
mask = make_source_mask(data, snr=2, npixels=5, dilate_size=11)
mean, median, std = sigma_clipped_stats(data, sigma=4.0, mask=mask)
backsub_data = data - mean
# fits.writeto('path_to_image_backsub.fits', backsub_data, head, overwrite=True)

In [ ]:
data = fits.getdata(datapath + '\\60.00s-0000.fits', ext=0)
head = fits.getheader(datapath + '\\60.00s-0000.fits', ext=0)

sigma_clip = SigmaClip(sigma=3.0, maxiters=10)
threshold = detect_threshold(data, nsigma=2.0, sigma_clip=sigma_clip)
segment_img = detect_sources(data, threshold, npixels=10)
footprint = circular_footprint(radius=10)
mask = segment_img.make_source_mask(footprint=footprint)
mean, median, std = sigma_clipped_stats(data, sigma=3.0, mask=mask)
print((mean, median, std))